services:
  algo-with-me-api:
    image: algo-with-me-api
    ports:
      - 3000:3000
    volumes:
      - /home/be/algo-with-me/problems/:/algo-with-me/problems/
      - /home/be/algo-with-me/submissions/:/algo-with-me/submissions/
      - /home/be/algo-with-me/testcases/:/algo-with-me/testcases/
    network_mode: host
    env_file:
      ./algo-with-me-api/.env
    user: be:be
    restart: always
  algo-with-me-score:
    image: algo-with-me-score
    ports:
      - 4000:4000
    volumes:
      - /home/be/algo-with-me/problems/:/algo-with-me/problems/
      - /home/be/algo-with-me/submissions/:/algo-with-me/submissions/
      - /home/be/algo-with-me/testcases/:/algo-with-me/testcases/
    network_mode: host
    env_file:
      - ./algo-with-me-score/.env
    user: be:be
    restart: always
  algo-with-me-docker:
    image: algo-with-me-docker
    ports:
      - 5000-5002:5000
    volumes:
      - /home/be/algo-with-me/problems/:/algo-with-me/problems/
      - /home/be/algo-with-me/submissions/:/algo-with-me/submissions/
      - /home/be/algo-with-me/testcases/:/algo-with-me/testcases/
    network_mode: bridge
    user: 1001:1001
    restart: always
    deploy:
      mode: replicated
      replicas: 3
