name: fe-dev 브랜치 깃허브 페이지스에 배포
on:
  push: # fe-dev 파일에 push가 되었을 때 실행해라!
    branches: ["fe-dev"]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Dependencies # 의존 파일 설치
        run: pnpm install
      - name: 빌드 실행
        run: pnpm run build
